[base]
name = 'Hass Panel'
web_port = 5124
env = "dev"
debug = true
user_config_dir = "../data/hass-panel-dev/user_configs"
upload_dir = '../data/hass-panel-dev/upload'
go2rtc_config_path = "../data/hass-panel-dev/go2rtc.yaml"
cache_dir = "../data/hass-panel-dev/cache"

[update_cfg]
github_repo = "mrtian2016/hass-panel"
app_dir = "../frontend/build"
version_file = "../frontend/build/version.json"
tmp_dir = "/tmp/hass-panel-update"
exclude_path = ["media", "env.js", "env.template.js"]


[log]
server_log = "../data/hass-panel-dev/logs"
log_output_dir = "../data/hass-panel-dev/logs/backend"

[database]
sqlite_path = "../data/hass-panel-dev/hass_panel.db"

[security]
SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 30
schemes = ["bcrypt"]

