[base]
name = 'Hass Panel'
web_port = 5124
env = "prod"
debug = false
user_config_dir = "/config/hass-panel/user_configs"
upload_dir = "/config/hass-panel/upload"
go2rtc_config_path = "/config/hass-panel/go2rtc.yaml"
cache_dir = "/config/hass-panel/cache"

[update_cfg]
github_repo = "mrtian2016/hass-panel"
app_dir = "/app"
version_file = "/app/version.json"
tmp_dir = "/tmp/hass-panel-update"
exclude_path = ["media", "env.js", "env.template.js"]

[log]
server_log = "/config/hass-panel/logs"
log_output_dir = "/config/hass-panel/logs/backend"

[database]
sqlite_path = "/config/hass-panel/hass_panel.db"

[security]
SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 30
schemes = ["bcrypt"]

