version: '3'

services:
  hass-panel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    hostname: hass-panel3
    volumes:
      - ../data/hass-panel-prod:/config/hass-panel
    restart: unless-stopped
    ports:
      - "5124:5124"
      - "5123:5123"