FROM python:3.9-slim

# 安装依赖
RUN apt-get update && apt-get install -y \
    nginx \
    curl \
    tzdata \
    supervisor \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# 安装 Python 依赖
RUN pip install --no-cache-dir --upgrade pip && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple \
    fastapi \
    uvicorn[standard] \
    requests \
    loguru \
    toml \
    omegaconf \
    aiohttp \
    python-multipart \
    pyyaml \
    sqlalchemy \
    pyjwt \
    passlib[bcrypt] \
    apscheduler \
    onvif-zeep

# 创建必要的目录
RUN mkdir -p /config/hass-panel

# 复制配置文件
COPY docker/config/nginx.conf /etc/nginx/sites-available/default
COPY docker/config/supervisord.conf /etc/supervisord.conf

# 创建工作目录
WORKDIR /backend

# 复制后端文件
COPY backend /backend

# 设置默认环境变量
ENV IS_ADDON=false
ENV PYTHONPATH=/backend

# 暴露端口
EXPOSE 5123 5124

# 启动命令
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]